### ISSUE TITLE
조건에 맞는 영상 조회 구현

### ISSUE THREAD

**Issue by horsehair** [DeliverBle/deliverble-backend#7]
## 5에 이어서, 조건에 맞는 영상 조회 구현
(현재 /news/search 로 엔드포인트 설정되어 있는 api)

### 조회 조건
- channel
- speaker(발화자 성별로, 속성명 변경 필요)
- category

1. 하나의 조건에 대하여 OR 조건,
2. 복수의 조건끼리 AND 조건.

**Comment by sigridjineth** [comment]
TypeORM find OR operator와 같은 키워드로 검색할 수 있다.
[출처](https://orkhan.gitbook.io/typeorm/docs/find-options)

예시:
```
userRepository.find({
    where: [
        { firstName: "Timber", lastName: "Saw" },
        { firstName: "Stan", lastName: "Lee" },
    ],
});
```
